import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

export type Language = 'english' | 'italian' | 'spanish' | 'german';
export type Currency = 'eur' | 'usd' | 'gbp' | 'chf';
export type Timezone = 'europe_rome' | 'europe_london' | 'europe_zurich' | 'america_newyork';

interface DisplaySettings {
  language: Language;
  currency: Currency;
  timezone: Timezone;
}

interface LanguageContextType {
  displaySettings: DisplaySettings;
  updateDisplaySettings: (settings: Partial<DisplaySettings>) => void;
  t: (key: string) => string; // Translation function
}

const defaultSettings: DisplaySettings = {
  language: 'english',
  currency: 'eur',
  timezone: 'europe_rome',
};

// Get saved settings from localStorage or use defaults
const getInitialSettings = (): DisplaySettings => {
  if (typeof window === 'undefined') return defaultSettings;
  
  const savedSettings = localStorage.getItem('displaySettings');
  return savedSettings ? JSON.parse(savedSettings) : defaultSettings;
};

// Translations dictionary
const translations: Record<Language, Record<string, string>> = {
  english: {
    // Navigation & Common elements
    home: 'Home',
    properties: 'Properties',
    events: 'Events',
    contact: 'Contact',
    aboutUs: 'About Us',
    login: 'Login',
    dashboard: 'Dashboard',
    analytics: 'Analytics',
    network: 'Network',
    profile: 'Profile',
    settings: 'Settings',
    language: 'Language',
    logout: 'Logout',
    
    // Dashboard components
    totalInvestment: 'Total Investment',
    roi: 'ROI',
    property: 'Property',
    location: 'Location',
    value: 'Value',
    status: 'Status',
    active: 'Active',
    development: 'Development',
    
    // Settings tabs
    notifications: 'Notifications',
    account: 'Account',
    preferences: 'Preferences',
    notificationSettings: 'Notification Settings',
    securitySettings: 'Security Settings',
    displayPreferences: 'Display Preferences',
    
    // Other common strings
    saveSettings: 'Save Settings',
    savePreferences: 'Save Preferences',
    saveNotificationSettings: 'Save Notification Settings',
    saveSecuritySettings: 'Save Security Settings',
    
    // Login page
    signIn: 'Sign in',
    signingIn: 'Signing in...',
    email: 'Email',
    password: 'Password',
    forgotPassword: 'Forgot password?',
    loginSuccessTitle: 'Success!',
    loginSuccessMsg: 'You have successfully logged in.',
    investorPortal: 'Investor Portal',
    investorPortalDesc: 'Sign in to access your exclusive investment dashboard',
    privatePortalAlert: 'This is a private investment portal. Access is granted only to verified investors.',
    needAssistance: 'Need assistance? Contact your investment advisor.',
    scheduleMeeting: 'Schedule a meeting',
    
    // Dashboard page
    investmentGrowth: 'Investment Growth',
    portfolioAllocation: 'Portfolio Allocation',
    yourProperties: 'Your Properties',
    
    // Events page
    upcomingEvents: 'Upcoming Events',
    pastEvents: 'Past Events',
    eventsFound: 'events found',
    rsvpConfirmed: 'RSVP Confirmed',
    rsvpConfirmedMsg: 'You\'ve successfully registered for:',
    downloadStarted: 'Download Started',
    downloadStartedMsg: 'Your recording download has started.',
    online: 'Online',
    inPerson: 'In-Person',
    viewDetails: 'View Details',
    rsvp: 'RSVP',
    capacity: 'Capacity',
    limitedTo: 'Limited to',
    investors: 'investors',
    unlimited: 'Unlimited',
    exclusiveEvents: 'Exclusive investment events and networking opportunities',
    
    // Network page
    investorNetwork: 'Investor Network',
    connectInvestors: 'Connect with fellow exclusive investors in the EasyROI community',
    searchInvestors: 'Search by name, location, or investment interest...',
    investorsFound: 'investors found',
    connectionSent: 'Connection Request Sent',
    connectionSentMsg: 'Your connection request has been sent to',
    messageCenter: 'Message Center',
    openingConversation: 'Opening conversation with',
    message: 'Message',
    connect: 'Connect',
    properties_count: 'Properties',
    
    // Analytics page
    comprehensiveAnalysis: 'Comprehensive data analysis of your investment portfolio',
    portfolioROI: 'Portfolio ROI',
    annualGrowth: 'Annual Growth',
    marketComparison: 'Market Comparison',
    aboveIndex: 'Above index',
    vsMarketAverage: 'vs market average',
    vsPreviousYear: 'vs previous year',
    roiPerformance: 'ROI Performance',
    yourPortfolio: 'Your Portfolio',
    marketAverage: 'Market Average',
    assetAllocation: 'Asset Allocation',
    allocation: 'Allocation',
    geographicDistribution: 'Geographic Distribution',
    historicalROI: 'Historical ROI Performance',
    annualROI: 'Annual ROI',
    
    // Landing page
    premiumRealEstate: 'Premium Real Estate',
    exceptionalReturns: 'Exceptional Returns',
    exclusiveAccess: 'Exclusive access to high-yield international real estate investments.',
    startInvesting: 'Start Investing',
    scroll: 'SCROLL',
    curated: 'Luxury portfolio carefully curated',
    curatedDesc: 'Access to exclusive real estate opportunities not available on the open market.',
    premiumProperties: 'Premium Properties',
    premiumPropertiesDesc: 'Access exclusive real estate in Italy, Dubai, and other luxury markets.',
    portfolioAnalytics: 'Portfolio Analytics',
    portfolioAnalyticsDesc: 'Track investments with comprehensive real-time data analysis.',
    securePlatform: 'Secure Platform',
    securePlatformDesc: 'Enterprise-grade security for your investments and data.',
    featuredLocations: 'Featured Locations',
    readyToMaximize: 'Ready to maximize your investment potential?',
    
    // Contact page
    contactUs: 'Contact Us',
    contactDescription: 'Have a question or need assistance with your investments? Our team of experts is here to help you.',
    contactInfo: 'Contact Information',
    visitUs: 'Visit Us',
    emailUs: 'Email Us',
    callUs: 'Call Us',
    businessHours: 'Business Hours',
    mondayToFriday: 'Monday to Friday',
    sendMessage: 'Send Us a Message',
    fullName: 'Full Name',
    fullNamePlaceholder: 'John Smith',
    emailPlaceholder: 'your@email.com',
    subject: 'Subject',
    subjectPlaceholder: 'How can we help you?',
    messagePlaceholder: 'Your message here...',
    
    // About Us page
    aboutUsTitle: 'About EasyROI',
    aboutUsSubtitle: 'Exclusive access to premium real estate investments designed for discerning investors.',
    ourStory: 'Our Story',
    ourStoryText1: 'EasyROI was founded by a team of real estate and investment experts with a shared vision: to create an exclusive community where discerning investors can access premium real estate opportunities with exceptional returns.',
    ourStoryText2: 'We understand that true wealth creation requires both exclusive access and sophisticated insights. Our carefully curated portfolio spans luxury markets across Italy, Dubai, and beyond, focusing on properties with high appreciation potential and superior ROI.',
    ourValues: 'Our Values',
    excellenceValue: 'Excellence',
    excellenceText: 'We hold ourselves to the highest standard in every aspect of our business, from property selection to client service.',
    integrityValue: 'Integrity',
    integrityText: 'We build trust through transparency, honesty, and ethical practices in all our dealings.',
    exclusivityValue: 'Exclusivity',
    exclusivityText: 'We provide our select community with access to opportunities not available on the open market.',
    joinOurCommunity: 'Join Our Exclusive Community',
    joinOurCommunityText: 'EasyROI offers more than just investments - it provides membership in an exclusive network of sophisticated investors who understand the value of premium opportunities.',
    loginCta: 'Access Your Portfolio',
    
    // Footer
    footerDescription: 'Premium real estate investment opportunities in Italy, Dubai, and beyond. Maximize your ROI with our exclusive portfolio and expert management.',
    quickLinks: 'Quick Links',
    
    // Language change messages
    languageChanged: 'Language changed to English',
    languageChangedItalian: 'Lingua cambiata in Italiano',
    languageChangedSpanish: 'Idioma cambiado a Español',
    languageChangedGerman: 'Sprache auf Deutsch geändert',
    
    // Registration page
    firstNameRequired: 'First name is required',
    lastNameRequired: 'Last name is required',
    invalidEmail: 'Invalid email address',
    passwordMinChars: 'Password must be at least 8 characters',
    acceptTermsRequired: 'You must accept the terms and conditions',
    passwordsNotMatch: 'Passwords do not match',
    registrationSuccess: 'Registration successful!',
    accountCreated: 'Your account has been created.',
    firstName: 'First name',
    lastName: 'Last name',
    confirmPassword: 'Confirm Password',
    iAccept: 'I accept the',
    termsAndConditions: 'terms and conditions',
    creatingAccount: 'Creating account...',
    alreadyHaveAccount: 'Already have an account?',
    joinCommunity: 'Join our exclusive investor community',
    firstNamePlaceholder: 'John',
    lastNamePlaceholder: 'Doe',
    
    // Properties page
    filterProperties: 'Filter Properties',
    showFilters: 'Show Filters',
    hideFilters: 'Hide Filters',
    allLocations: 'All Locations',
    allPrices: 'All Prices',
    allLevels: 'All Levels',
    priceRange: 'Price Range',
    investorLevel: 'Investor Level',
    resetFilters: 'Reset Filters',
    applyFilters: 'Apply Filters',
    minInvestment: 'Min Investment',
    expectedROI: 'Expected ROI',
    exclusiveProperties: 'Exclusive Properties',
    discoverProperties: 'Discover our handpicked selection of luxury real estate investments in premier locations around the world.',
    amenities: 'Amenities',
    
    // Settings page
    manageSettings: 'Manage your account settings and preferences',
    accountSettings: 'Account Settings',
    accountSettingsDesc: 'View and manage your account details',
    displaySettings: 'Display Settings',
    displaySettingsDesc: 'Customize your display preferences',
    notificationSettingsDesc: 'Manage your notification preferences',
    privacySettings: 'Privacy Settings',
    privacySettingsDesc: 'Control your privacy preferences',
    name: 'Name',
    selectLanguage: 'Select language',
    selectCurrency: 'Select currency',
    selectTimezone: 'Select timezone',
    currency: 'Currency',
    timezone: 'Timezone',
    emailNotifications: 'Email Notifications',
    emailNotificationsDesc: 'Receive notifications via email',
    pushNotifications: 'Push Notifications',
    pushNotificationsDesc: 'Receive push notifications',
    publicProfile: 'Public Profile',
    publicProfileDesc: 'Make your profile visible to other users',
    dataSharing: 'Data Sharing',
    dataSharingDesc: 'Allow us to share your data with partners',
    saving: 'Saving...',
    updateAccount: 'Update Account',
    updateDisplay: 'Update Display',
    updateNotifications: 'Update Notifications',
    updatePrivacy: 'Update Privacy',
    accountSettingsUpdated: 'Account Settings Updated',
    accountSettingsSaved: 'Your account settings have been saved.',
    displaySettingsUpdated: 'Display Settings Updated',
    displaySettingsSaved: 'Your display settings have been saved.',
    notificationSettingsUpdated: 'Notification Settings Updated',
    notificationSettingsSaved: 'Your notification settings have been saved.',
    privacySettingsUpdated: 'Privacy Settings Updated',
    privacySettingsSaved: 'Your privacy settings have been saved.',
    errorOccurred: 'Error Occurred',
    errorLoadingSettings: 'Error loading settings. Please try again.',
    errorUpdatingSettings: 'Error updating settings. Please try again.',
  },
  italian: {
    // Navigation & Common elements
    home: 'Home',
    properties: 'Proprietà',
    events: 'Eventi',
    contact: 'Contatti',
    aboutUs: 'Chi Siamo',
    login: 'Accedi',
    dashboard: 'Dashboard',
    analytics: 'Analisi',
    network: 'Rete',
    profile: 'Profilo',
    settings: 'Impostazioni',
    language: 'Lingua',
    logout: 'Esci',
    
    // Dashboard components
    totalInvestment: 'Investimento Totale',
    roi: 'ROI',
    property: 'Proprietà',
    location: 'Posizione',
    value: 'Valore',
    status: 'Stato',
    active: 'Attivo',
    development: 'Sviluppo',
    
    // Settings tabs
    notifications: 'Notifiche',
    account: 'Account',
    preferences: 'Preferenze',
    notificationSettings: 'Impostazioni Notifiche',
    securitySettings: 'Impostazioni Sicurezza',
    displayPreferences: 'Preferenze Display',
    
    // Other common strings
    saveSettings: 'Salva Impostazioni',
    savePreferences: 'Salva Preferenze',
    saveNotificationSettings: 'Salva Impostazioni Notifiche',
    saveSecuritySettings: 'Salva Impostazioni Sicurezza',
    
    // Login page
    signIn: 'Accedi',
    signingIn: 'Accesso in corso...',
    email: 'Email',
    password: 'Password',
    forgotPassword: 'Password dimenticata?',
    loginSuccessTitle: 'Successo!',
    loginSuccessMsg: 'Hai effettuato l\'accesso con successo.',
    investorPortal: 'Portale Investitori',
    investorPortalDesc: 'Accedi per visualizzare la tua dashboard di investimenti esclusiva',
    privatePortalAlert: 'Questo è un portale di investimento privato. L\'accesso è consentito solo agli investitori verificati.',
    needAssistance: 'Hai bisogno di assistenza? Contatta il tuo consulente di investimenti.',
    scheduleMeeting: 'Richiedi una consulenza',
    
    // Dashboard page
    investmentGrowth: 'Crescita degli Investimenti',
    portfolioAllocation: 'Allocazione del Portafoglio',
    yourProperties: 'Le Tue Proprietà',
    
    // Events page
    upcomingEvents: 'Eventi Imminenti',
    pastEvents: 'Eventi Passati',
    eventsFound: 'eventi trovati',
    rsvpConfirmed: 'Registrazione Confermata',
    rsvpConfirmedMsg: 'Ti sei registrato con successo per:',
    downloadStarted: 'Download Avviato',
    downloadStartedMsg: 'Il download della registrazione è iniziato.',
    online: 'Online',
    inPerson: 'In Presenza',
    viewDetails: 'Vedi Dettagli',
    rsvp: 'Prenota',
    capacity: 'Capacità',
    limitedTo: 'Limitato a',
    investors: 'investitori',
    unlimited: 'Illimitato',
    exclusiveEvents: 'Eventi esclusivi di investimento e opportunità di networking',
    
    // Network page
    investorNetwork: 'Rete Investitori',
    connectInvestors: 'Connettiti con altri investitori esclusivi nella comunità EasyROI',
    searchInvestors: 'Cerca per nome, località o interesse di investimento...',
    investorsFound: 'investitori trovati',
    connectionSent: 'Richiesta di Connessione Inviata',
    connectionSentMsg: 'La tua richiesta di connessione è stata inviata a',
    messageCenter: 'Centro Messaggi',
    openingConversation: 'Apertura conversazione con',
    message: 'Messaggio',
    connect: 'Connetti',
    properties_count: 'Proprietà',
    
    // Analytics page
    comprehensiveAnalysis: 'Analisi completa del tuo portafoglio di investimenti',
    portfolioROI: 'ROI del Portafoglio',
    annualGrowth: 'Crescita Annuale',
    marketComparison: 'Confronto con il Mercato',
    aboveIndex: 'Sopra l\'indice',
    vsMarketAverage: 'vs media di mercato',
    vsPreviousYear: 'vs anno precedente',
    roiPerformance: 'Andamento ROI',
    yourPortfolio: 'Il Tuo Portafoglio',
    marketAverage: 'Media di Mercato',
    assetAllocation: 'Allocazione Asset',
    allocation: 'Allocazione',
    geographicDistribution: 'Distribuzione Geografica',
    historicalROI: 'Storico Andamento ROI',
    annualROI: 'ROI Annuale',
    
    // Landing page
    premiumRealEstate: 'Immobili di Pregio',
    exceptionalReturns: 'Rendimenti Eccezionali',
    exclusiveAccess: 'Accesso esclusivo a investimenti immobiliari internazionali ad alto rendimento.',
    startInvesting: 'Inizia ad Investire',
    scroll: 'SCORRI',
    curated: 'Portafoglio di lusso accuratamente selezionato',
    curatedDesc: 'Accesso a opportunità immobiliari esclusive non disponibili sul mercato aperto.',
    premiumProperties: 'Proprietà Premium',
    premiumPropertiesDesc: 'Accedi a immobili esclusivi in Italia, Dubai e altri mercati di lusso.',
    portfolioAnalytics: 'Analisi del Portafoglio',
    portfolioAnalyticsDesc: 'Monitora gli investimenti con analisi dei dati in tempo reale.',
    securePlatform: 'Piattaforma Sicura',
    securePlatformDesc: 'Sicurezza di livello enterprise per i tuoi investimenti e dati.',
    featuredLocations: 'Località in Evidenza',
    readyToMaximize: 'Pronto a massimizzare il tuo potenziale di investimento?',
    
    // Contact page
    contactUs: 'Contattaci',
    contactDescription: 'Hai domande o hai bisogno di assistenza con i tuoi investimenti? Il nostro team di esperti è qui per aiutarti.',
    contactInfo: 'Informazioni di Contatto',
    visitUs: 'Vieni a Trovarci',
    emailUs: 'Scrivici',
    callUs: 'Chiamaci',
    businessHours: 'Orari di Ufficio',
    mondayToFriday: 'Lunedì - Venerdì',
    sendMessage: 'Inviaci un Messaggio',
    fullName: 'Nome Completo',
    fullNamePlaceholder: 'Mario Rossi',
    emailPlaceholder: 'tua@email.com',
    subject: 'Oggetto',
    subjectPlaceholder: 'Come possiamo aiutarti?',
    messagePlaceholder: 'Il tuo messaggio qui...',
    
    // About Us page
    aboutUsTitle: 'Chi è EasyROI',
    aboutUsSubtitle: 'Accesso esclusivo a investimenti immobiliari premium progettati per investitori esigenti.',
    ourStory: 'La Nostra Storia',
    ourStoryText1: 'EasyROI è stata fondata da un team di esperti immobiliari e di investimento con una visione condivisa: creare una comunità esclusiva in cui investitori esigenti possano accedere a opportunità immobiliari premium con rendimenti eccezionali.',
    ourStoryText2: 'Comprendiamo che la vera creazione di ricchezza richiede sia accesso esclusivo che intuizioni sofisticate. Il nostro portafoglio accuratamente selezionato comprende mercati di lusso in Italia, Dubai e oltre, concentrandosi su proprietà con elevato potenziale di apprezzamento e ROI superiore.',
    ourValues: 'I Nostri Valori',
    excellenceValue: 'Eccellenza',
    excellenceText: 'Ci atteniamo ai più alti standard in ogni aspetto della nostra attività, dalla selezione delle proprietà al servizio clienti.',
    integrityValue: 'Integrità',
    integrityText: 'Costruiamo fiducia attraverso trasparenza, onestà e pratiche etiche in tutti i nostri rapporti.',
    exclusivityValue: 'Esclusività',
    exclusivityText: 'Forniamo alla nostra comunità selezionata accesso a opportunità non disponibili sul mercato aperto.',
    joinOurCommunity: 'Unisciti alla Nostra Community Esclusiva',
    joinOurCommunityText: 'EasyROI offre più di semplici investimenti: fornisce l\'appartenenza a una rete esclusiva di investitori sofisticati che comprendono il valore delle opportunità premium.',
    loginCta: 'Accedi al Tuo Portafoglio',
    
    // Footer
    footerDescription: 'Opportunità di investimento immobiliare di pregio in Italia, Dubai e oltre. Massimizza il tuo ROI con il nostro portafoglio esclusivo e la gestione esperta.',
    quickLinks: 'Link Rapidi',
    
    // Language change messages
    languageChanged: 'Language changed to English',
    languageChangedItalian: 'Lingua cambiata in Italiano',
    languageChangedSpanish: 'Idioma cambiado a Español',
    languageChangedGerman: 'Sprache auf Deutsch geändert',
    
    // Registration page
    firstNameRequired: 'Il nome è obbligatorio',
    lastNameRequired: 'Il cognome è obbligatorio',
    invalidEmail: 'Indirizzo email non valido',
    passwordMinChars: 'La password deve contenere almeno 8 caratteri',
    acceptTermsRequired: 'Devi accettare i termini e le condizioni',
    passwordsNotMatch: 'Le password non coincidono',
    registrationSuccess: 'Registrazione completata!',
    accountCreated: 'Il tuo account è stato creato.',
    firstName: 'Nome',
    lastName: 'Cognome',
    confirmPassword: 'Conferma Password',
    iAccept: 'Accetto i',
    termsAndConditions: 'termini e condizioni',
    creatingAccount: 'Creazione account in corso...',
    alreadyHaveAccount: 'Hai già un account?',
    joinCommunity: 'Unisciti alla nostra esclusiva comunità di investitori',
    firstNamePlaceholder: 'Mario',
    lastNamePlaceholder: 'Rossi',
    
    // Properties page
    filterProperties: 'Filtra Proprietà',
    showFilters: 'Mostra Filtri',
    hideFilters: 'Nascondi Filtri',
    allLocations: 'Tutte le Località',
    allPrices: 'Tutti i Prezzi',
    allLevels: 'Tutti i Livelli',
    priceRange: 'Fascia di Prezzo',
    investorLevel: 'Livello Investitore',
    resetFilters: 'Reimposta Filtri',
    applyFilters: 'Applica Filtri',
    minInvestment: 'Investimento Minimo',
    expectedROI: 'ROI Previsto',
    exclusiveProperties: 'Proprietà Esclusive',
    discoverProperties: 'Scopri la nostra selezione di investimenti immobiliari di lusso in location prestigiose in tutto il mondo.',
    amenities: 'Servizi',
    
    // Settings page
    manageSettings: 'Gestisci le impostazioni e le preferenze del tuo account',
    accountSettings: 'Impostazioni Account',
    accountSettingsDesc: 'Visualizza e gestisci i dettagli del tuo account',
    displaySettings: 'Impostazioni Display',
    displaySettingsDesc: 'Personalizza le tue preferenze di visualizzazione',
    notificationSettingsDesc: 'Gestisci le tue preferenze di notifica',
    privacySettings: 'Impostazioni Privacy',
    privacySettingsDesc: 'Controlla le tue preferenze di privacy',
    name: 'Nome',
    selectLanguage: 'Seleziona lingua',
    selectCurrency: 'Seleziona valuta',
    selectTimezone: 'Seleziona fuso orario',
    currency: 'Valuta',
    timezone: 'Fuso Orario',
    emailNotifications: 'Notifiche Email',
    emailNotificationsDesc: 'Ricevi notifiche via email',
    pushNotifications: 'Notifiche Push',
    pushNotificationsDesc: 'Ricevi notifiche push',
    publicProfile: 'Profilo Pubblico',
    publicProfileDesc: 'Rendi il tuo profilo visibile agli altri utenti',
    dataSharing: 'Condivisione Dati',
    dataSharingDesc: 'Consenti di condividere i tuoi dati con i partner',
    saving: 'Salvataggio...',
    updateAccount: 'Aggiorna Account',
    updateDisplay: 'Aggiorna Display',
    updateNotifications: 'Aggiorna Notifiche',
    updatePrivacy: 'Aggiorna Privacy',
    accountSettingsUpdated: 'Impostazioni Account Aggiornate',
    accountSettingsSaved: 'Le impostazioni del tuo account sono state salvate.',
    displaySettingsUpdated: 'Impostazioni Display Aggiornate',
    displaySettingsSaved: 'Le tue impostazioni di visualizzazione sono state salvate.',
    notificationSettingsUpdated: 'Impostazioni Notifiche Aggiornate',
    notificationSettingsSaved: 'Le tue impostazioni di notifica sono state salvate.',
    privacySettingsUpdated: 'Impostazioni Privacy Aggiornate',
    privacySettingsSaved: 'Le tue impostazioni di privacy sono state salvate.',
    errorOccurred: 'Errore',
    errorLoadingSettings: 'Errore durante il caricamento delle impostazioni. Riprova.',
    errorUpdatingSettings: 'Errore durante l\'aggiornamento delle impostazioni. Riprova.',
  },
  spanish: {
    // Navigation & Common elements
    home: 'Inicio',
    properties: 'Propiedades',
    events: 'Eventos',
    contact: 'Contacto',
    aboutUs: 'Quiénes Somos',
    login: 'Iniciar Sesión',
    dashboard: 'Panel',
    analytics: 'Análisis',
    network: 'Red',
    profile: 'Perfil',
    settings: 'Configuración',
    language: 'Idioma',
    logout: 'Cerrar Sesión',
    
    // Dashboard components
    totalInvestment: 'Inversión Total',
    roi: 'ROI',
    property: 'Propiedad',
    location: 'Ubicación',
    value: 'Valor',
    status: 'Estado',
    active: 'Activo',
    development: 'Desarrollo',
    
    // Settings tabs
    notifications: 'Notificaciones',
    account: 'Cuenta',
    preferences: 'Preferencias',
    notificationSettings: 'Configuración de Notificaciones',
    securitySettings: 'Configuración de Seguridad',
    displayPreferences: 'Preferencias de Pantalla',
    
    // Other common strings
    saveSettings: 'Guardar Configuración',
    savePreferences: 'Guardar Preferencias',
    saveNotificationSettings: 'Guardar Configuración de Notificaciones',
    saveSecuritySettings: 'Guardar Configuración de Seguridad',
    
    // Login page
    signIn: 'Iniciar Sesión',
    signingIn: 'Iniciando sesión...',
    email: 'Email',
    password: 'Contraseña',
    forgotPassword: '¿Olvidaste tu contraseña?',
    loginSuccessTitle: '¡Éxito!',
    loginSuccessMsg: 'Has iniciado sesión correctamente.',
    investorPortal: 'Portal de Inversores',
    investorPortalDesc: 'Inicia sesión para acceder a tu panel de inversiones exclusivo',
    privatePortalAlert: 'Este es un portal de inversión privado. El acceso se concede solo a inversores verificados.',
    needAssistance: '¿Necesitas ayuda? Contacta a tu asesor de inversiones.',
    scheduleMeeting: 'Agende su consulta',
    
    // Dashboard page
    investmentGrowth: 'Crecimiento de Inversión',
    portfolioAllocation: 'Asignación de Portafolio',
    yourProperties: 'Tus Propiedades',
    
    // Events page
    upcomingEvents: 'Próximos Eventos',
    pastEvents: 'Eventos Pasados',
    eventsFound: 'eventos encontrados',
    rsvpConfirmed: 'Confirmación de Asistencia',
    rsvpConfirmedMsg: 'Te has registrado exitosamente para:',
    downloadStarted: 'Descarga Iniciada',
    downloadStartedMsg: 'La descarga de tu grabación ha comenzado.',
    online: 'En Línea',
    inPerson: 'Presencial',
    viewDetails: 'Ver Detalles',
    rsvp: 'Reservar',
    capacity: 'Capacidad',
    limitedTo: 'Limitado a',
    investors: 'inversores',
    unlimited: 'Ilimitado',
    exclusiveEvents: 'Eventos exclusivos de inversión y oportunidades de networking',
    
    // Network page
    investorNetwork: 'Red de Inversores',
    connectInvestors: 'Conéctate con inversores exclusivos en la comunidad EasyROI',
    searchInvestors: 'Buscar por nombre, ubicación o interés de inversión...',
    investorsFound: 'inversores encontrados',
    connectionSent: 'Solicitud de Conexión Enviada',
    connectionSentMsg: 'Tu solicitud de conexión ha sido enviada a',
    messageCenter: 'Centro de Mensajes',
    openingConversation: 'Abriendo conversación con',
    message: 'Mensaje',
    connect: 'Conectar',
    properties_count: 'Propiedades',
    
    // Analytics page
    comprehensiveAnalysis: 'Análisis completo de tu cartera de inversiones',
    portfolioROI: 'ROI de Cartera',
    annualGrowth: 'Crecimiento Anual',
    marketComparison: 'Comparación con el Mercado',
    aboveIndex: 'Por encima del índice',
    vsMarketAverage: 'vs promedio del mercado',
    vsPreviousYear: 'vs año anterior',
    roiPerformance: 'Rendimiento ROI',
    yourPortfolio: 'Tu Cartera',
    marketAverage: 'Promedio del Mercado',
    assetAllocation: 'Asignación de Activos',
    allocation: 'Asignación',
    geographicDistribution: 'Distribución Geográfica',
    historicalROI: 'Historial de Rendimiento ROI',
    annualROI: 'ROI Anual',
    
    // Landing page
    premiumRealEstate: 'Inmuebles Premium',
    exceptionalReturns: 'Retornos Excepcionales',
    exclusiveAccess: 'Acceso exclusivo a inversiones inmobiliarias internacionales de alto rendimiento.',
    startInvesting: 'Comenzar a Invertir',
    scroll: 'DESPLAZAR',
    curated: 'Portafoglio de lujo cuidadosamente seleccionado',
    curatedDesc: 'Acceso a oportunidades inmobiliarias exclusivas no disponibles en el mercado abierto.',
    premiumProperties: 'Propiedades Premium',
    premiumPropertiesDesc: 'Accede a inmuebles exclusivos en Italia, Dubai y otros mercados de lujo.',
    portfolioAnalytics: 'Análisis de Portafolio',
    portfolioAnalyticsDesc: 'Rastrea inversiones con análisis de datos completos en tiempo real.',
    securePlatform: 'Plataforma Segura',
    securePlatformDesc: 'Seguridad empresarial para tus inversiones y datos.',
    featuredLocations: 'Ubicaciones Destacadas',
    readyToMaximize: '¿Listo para maximizar tu potencial de inversion?',
    
    // Contact page
    contactUs: 'Contáctanos',
    contactDescription: '¿Tienes preguntas o necesitas ayuda con tus inversiones? Nuestro equipo de expertos está aquí para ayudarte.',
    contactInfo: 'Información de Contacto',
    visitUs: 'Visítanos',
    emailUs: 'Escríbenos',
    callUs: 'Llámanos',
    businessHours: 'Horario de Oficina',
    mondayToFriday: 'Lunes a Viernes',
    sendMessage: 'Envíanos un Mensaje',
    fullName: 'Nombre Completo',
    fullNamePlaceholder: 'Juan Pérez',
    emailPlaceholder: 'tu@email.com',
    subject: 'Asunto',
    subjectPlaceholder: '¿Cómo podemos ayudarte?',
    messagePlaceholder: 'Tu mensaje aquí...',
    
    // About Us page
    aboutUsTitle: 'Acerca de EasyROI',
    aboutUsSubtitle: 'Acceso exclusivo a inversiones inmobiliarias premium diseñadas para inversores exigentes.',
    ourStory: 'Nuestra Historia',
    ourStoryText1: 'EasyROI fue fundada por un equipo de expertos inmobiliarios y de inversión con una visión compartida: crear una comunidad exclusiva donde inversores exigentes puedan acceder a oportunidades inmobiliarias premium con rendimientos excepcionales.',
    ourStoryText2: 'Entendemos que la verdadera creación de riqueza requiere tanto acceso exclusivo como ideas sofisticadas. Nuestro portafolio cuidadosamente seleccionado abarca mercados de lujo en Italia, Dubai y más allá, centrándose en propiedades con alto potencial de apreciación y ROI superior.',
    ourValues: 'Nuestros Valores',
    excellenceValue: 'Excelencia',
    excellenceText: 'Nos regimos por los más altos estándares en cada aspecto de nuestro negocio, desde la selección de propiedades hasta el servicio al cliente.',
    integrityValue: 'Integridad',
    integrityText: 'Construimos confianza a través de la transparencia, la honestidad y las prácticas éticas en todas nuestras operaciones.',
    exclusivityValue: 'Exclusividad',
    exclusivityText: 'Proporcionamos a nuestra comunidad selecta acceso a oportunidades no disponibles en el mercado abierto.',
    joinOurCommunity: 'Únete a Nuestra Comunidad Exclusiva',
    joinOurCommunityText: 'EasyROI ofrece más que solo inversiones: proporciona membresía en una red exclusiva de inversores sofisticados que entienden el valor de las oportunidades premium.',
    loginCta: 'Accede a Tu Portafolio',
    
    // Footer
    footerDescription: 'Oportunidades de inversión inmobiliaria premium en Italia, Dubai y más allá. Maximiza tu ROI con nuestro portafolio exclusivo y gestión experta.',
    quickLinks: 'Enlaces Rápidos',
    
    // Language change messages
    languageChanged: 'Language changed to English',
    languageChangedItalian: 'Lingua cambiata in Italiano',
    languageChangedSpanish: 'Idioma cambiado a Español',
    languageChangedGerman: 'Sprache auf Deutsch geändert',
    
    // Registration page
    firstNameRequired: 'El nombre es obligatorio',
    lastNameRequired: 'El apellido es obligatorio',
    invalidEmail: 'Dirección de correo inválida',
    passwordMinChars: 'La contraseña debe tener al menos 8 caracteres',
    acceptTermsRequired: 'Debes aceptar los términos y condiciones',
    passwordsNotMatch: 'Las contraseñas no coinciden',
    registrationSuccess: '¡Registro exitoso!',
    accountCreated: 'Tu cuenta ha sido creada.',
    firstName: 'Nombre',
    lastName: 'Apellido',
    confirmPassword: 'Confirmar Contraseña',
    iAccept: 'Acepto los',
    termsAndConditions: 'términos y condiciones',
    creatingAccount: 'Creando cuenta...',
    alreadyHaveAccount: '¿Ya tienes una cuenta?',
    joinCommunity: 'Únete a nuestra comunidad exclusiva de inversores',
    firstNamePlaceholder: 'Juan',
    lastNamePlaceholder: 'Pérez',
    
    // Properties page
    filterProperties: 'Filtrar Propiedades',
    showFilters: 'Mostrar Filtros',
    hideFilters: 'Ocultar Filtros',
    allLocations: 'Todas las Ubicaciones',
    allPrices: 'Todos los Precios',
    allLevels: 'Todos los Niveles',
    priceRange: 'Rango de Precio',
    investorLevel: 'Nivel de Inversor',
    resetFilters: 'Restablecer Filtros',
    applyFilters: 'Aplicar Filtros',
    minInvestment: 'Inversión Mínima',
    expectedROI: 'ROI Esperado',
    exclusiveProperties: 'Propiedades Exclusivas',
    discoverProperties: 'Descubre nuestra selección de inversiones inmobiliarias de lujo en ubicaciones privilegiadas de todo el mundo.',
    amenities: 'Comodidades',
    
    // Settings page
    manageSettings: 'Gestiona la configuración y preferencias de tu cuenta',
    accountSettings: 'Configuración de Cuenta',
    accountSettingsDesc: 'Ver y gestionar los detalles de tu cuenta',
    displaySettings: 'Configuración de Pantalla',
    displaySettingsDesc: 'Personaliza tus preferencias de visualización',
    notificationSettingsDesc: 'Gestiona tus preferencias de notificación',
    privacySettings: 'Configuración de Privacidad',
    privacySettingsDesc: 'Controla tus preferencias de privacidad',
    name: 'Nombre',
    selectLanguage: 'Seleccionar idioma',
    selectCurrency: 'Seleccionar moneda',
    selectTimezone: 'Seleccionar zona horaria',
    currency: 'Moneda',
    timezone: 'Zona Horaria',
    emailNotifications: 'Notificaciones por Email',
    emailNotificationsDesc: 'Recibir notificaciones por correo electrónico',
    pushNotifications: 'Notificaciones Push',
    pushNotificationsDesc: 'Recibir notificaciones push',
    publicProfile: 'Perfil Público',
    publicProfileDesc: 'Hacer tu perfil visible para otros usuarios',
    dataSharing: 'Compartir Datos',
    dataSharingDesc: 'Permitir compartir tus datos con socios',
    saving: 'Guardando...',
    updateAccount: 'Actualizar Cuenta',
    updateDisplay: 'Actualizar Pantalla',
    updateNotifications: 'Actualizar Notificaciones',
    updatePrivacy: 'Actualizar Privacidad',
    accountSettingsUpdated: 'Configuración de Cuenta Actualizada',
    accountSettingsSaved: 'La configuración de tu cuenta ha sido guardada.',
    displaySettingsUpdated: 'Configuración de Pantalla Actualizada',
    displaySettingsSaved: 'Tu configuración de pantalla ha sido guardada.',
    notificationSettingsUpdated: 'Configuración de Notificaciones Actualizada',
    notificationSettingsSaved: 'Tu configuración de notificaciones ha sido guardada.',
    privacySettingsUpdated: 'Configuración de Privacidad Actualizada',
    privacySettingsSaved: 'Tu configuración de privacidad ha sido guardada.',
    errorOccurred: 'Error',
    errorLoadingSettings: 'Error al cargar la configuración. Por favor, inténtalo de nuevo.',
    errorUpdatingSettings: 'Error al actualizar la configuración. Por favor, inténtalo de nuevo.',
  },
  german: {
    // Navigation & Common elements
    home: 'Startseite',
    properties: 'Immobilien',
    events: 'Veranstaltungen',
    contact: 'Kontakt',
    aboutUs: 'Über Uns',
    login: 'Anmelden',
    dashboard: 'Dashboard',
    analytics: 'Analysen',
    network: 'Netzwerk',
    profile: 'Profil',
    settings: 'Einstellungen',
    language: 'Sprache',
    logout: 'Abmelden',
    
    // Dashboard components
    totalInvestment: 'Gesamtinvestition',
    roi: 'ROI',
    property: 'Immobilie',
    location: 'Standort',
    value: 'Wert',
    status: 'Status',
    active: 'Aktiv',
    development: 'Entwicklung',
    
    // Settings tabs
    notifications: 'Benachrichtigungen',
    account: 'Konto',
    preferences: 'Präferenzen',
    notificationSettings: 'Benachrichtigungseinstellungen',
    securitySettings: 'Sicherheitseinstellungen',
    displayPreferences: 'Anzeigeeinstellungen',
    
    // Other common strings
    saveSettings: 'Einstellungen Speichern',
    savePreferences: 'Präferenzen Speichern',
    saveNotificationSettings: 'Benachrichtigungseinstellungen Speichern',
    saveSecuritySettings: 'Sicherheitseinstellungen Speichern',
    
    // Login page
    signIn: 'Anmelden',
    signingIn: 'Anmeldung läuft...',
    email: 'E-Mail',
    password: 'Passwort',
    forgotPassword: 'Passwort vergessen?',
    loginSuccessTitle: 'Erfolg!',
    loginSuccessMsg: 'Du hast dich erfolgreich angemeldet.',
    investorPortal: 'Investorenportal',
    investorPortalDesc: 'Melde dich an, um auf dein exklusives Investoren-Dashboard zuzugreifen',
    privatePortalAlert: 'Dies ist ein privates Investitionsportal. Der Zugang wird nur verifizierten Investoren gewährt.',
    needAssistance: 'Brauchst du Hilfe? Kontaktiere deinen Anlageberater.',
    scheduleMeeting: 'Beratung buchen',
    
    // Dashboard page
    investmentGrowth: 'Investitionswachstum',
    portfolioAllocation: 'Portfolio-Allokation',
    yourProperties: 'Deine Immobilien',
    
    // Events page
    upcomingEvents: 'Kommende Veranstaltungen',
    pastEvents: 'Vergangene Veranstaltungen',
    eventsFound: 'Veranstaltungen gefunden',
    rsvpConfirmed: 'Anmeldung Bestätigt',
    rsvpConfirmedMsg: 'Du hast dich erfolgreich registriert für:',
    downloadStarted: 'Download Gestartet',
    downloadStartedMsg: 'Der Download deiner Aufzeichnung hat begonnen.',
    online: 'Online',
    inPerson: 'Vor Ort',
    viewDetails: 'Details Anzeigen',
    rsvp: 'Anmelden',
    capacity: 'Kapazität',
    limitedTo: 'Begrenzt auf',
    investors: 'Investoren',
    unlimited: 'Unbegrenzt',
    exclusiveEvents: 'Exklusive Investitionsveranstaltungen und Networking-Möglichkeiten',
    
    // Network page
    investorNetwork: 'Investorennetzwerk',
    connectInvestors: 'Verbinde dich mit anderen exklusiven Investoren in der EasyROI-Community',
    searchInvestors: 'Suche nach Name, Standort oder Investitionsinteresse...',
    investorsFound: 'Investoren gefunden',
    connectionSent: 'Verbindungsanfrage Gesendet',
    connectionSentMsg: 'Deine Verbindungsanfrage wurde gesendet an',
    messageCenter: 'Nachrichtenzentrale',
    openingConversation: 'Öffne Konversation mit',
    message: 'Nachricht',
    connect: 'Verbinden',
    properties_count: 'Immobilien',
    
    // Analytics page
    comprehensiveAnalysis: 'Umfassende Datenanalyse deines Investitionsportfolios',
    portfolioROI: 'Portfolio-ROI',
    annualGrowth: 'Jährliches Wachstum',
    marketComparison: 'Marktvergleich',
    aboveIndex: 'Über dem Index',
    vsMarketAverage: 'vs. Marktdurchschnitt',
    vsPreviousYear: 'vs. Vorjahr',
    roiPerformance: 'ROI-Performance',
    yourPortfolio: 'Dein Portfolio',
    marketAverage: 'Marktdurchschnitt',
    assetAllocation: 'Asset-Allokation',
    allocation: 'Allokation',
    geographicDistribution: 'Geografische Verteilung',
    historicalROI: 'Historische ROI-Performance',
    annualROI: 'Jährlicher ROI',
    
    // Landing page
    premiumRealEstate: 'Premium-Immobilien',
    exceptionalReturns: 'Außergewöhnliche Renditen',
    exclusiveAccess: 'Exklusiver Zugang zu renditestarken internationalen Immobilieninvestitionen.',
    startInvesting: 'Jetzt Investieren',
    scroll: 'SCROLLEN',
    curated: 'Sorgfältig zusammengestelltes Luxusportfolio',
    curatedDesc: 'Zugang zu exklusiven Immobilienangeboten, die auf dem offenen Markt nicht verfügbar sind.',
    premiumProperties: 'Premium-Immobilien',
    premiumPropertiesDesc: 'Zugang zu exklusiven Immobilien in Italien, Dubai und anderen Luxusmärkten.',
    portfolioAnalytics: 'Portfolio-Analysen',
    portfolioAnalyticsDesc: 'Verfolge Investitionen mit umfassender Echtzeitdatenanalyse.',
    securePlatform: 'Sichere Plattform',
    securePlatformDesc: 'Unternehmenssichere Plattform für deine Investitionen und Daten.',
    featuredLocations: 'Ausgewählte Standorte',
    readyToMaximize: 'Bereit, dein Investitionspotenzial zu maximieren?',
    
    // Contact page
    contactUs: 'Kontaktiere Uns',
    contactDescription: 'Hast du Fragen oder benötigst Unterstützung bei deinen Investitionen? Unser Expertenteam steht dir zur Verfügung.',
    contactInfo: 'Kontaktinformationen',
    visitUs: 'Besuche Uns',
    emailUs: 'E-Mail an Uns',
    callUs: 'Ruf Uns an',
    businessHours: 'Geschäftszeiten',
    mondayToFriday: 'Montag bis Freitag',
    sendMessage: 'Sende Uns eine Nachricht',
    fullName: 'Vollständiger Name',
    fullNamePlaceholder: 'Hans Schmidt',
    emailPlaceholder: 'deine@email.com',
    subject: 'Betreff',
    subjectPlaceholder: 'Wie können wir dir helfen?',
    messagePlaceholder: 'Deine Nachricht hier...',
    
    // About Us page
    aboutUsTitle: 'Über EasyROI',
    aboutUsSubtitle: 'Exklusiver Zugang zu Premium-Immobilieninvestitionen für anspruchsvolle Investoren.',
    ourStory: 'Unsere Geschichte',
    ourStoryText1: 'EasyROI wurde von einem Team aus Immobilien- und Investmentexperten mit einer gemeinsamen Vision gegründet: eine exklusive Gemeinschaft zu schaffen, in der anspruchsvolle Investoren Zugang zu erstklassigen Immobilienmöglichkeiten mit außergewöhnlichen Renditen erhalten.',
    ourStoryText2: 'Wir verstehen, dass echte Vermögensbildung sowohl exklusiven Zugang als auch anspruchsvolle Einblicke erfordert. Unser sorgfältig zusammengestelltes Portfolio umfasst Luxusmärkte in Italien, Dubai und darüber hinaus, mit Fokus auf Immobilien mit hohem Wertsteigerungspotenzial und überlegener Rendite.',
    ourValues: 'Unsere Werte',
    excellenceValue: 'Exzellenz',
    excellenceText: 'Wir halten uns in jedem Aspekt unseres Geschäfts an höchste Standards, von der Immobilienauswahl bis zum Kundenservice.',
    integrityValue: 'Integrität',
    integrityText: 'Wir schaffen Vertrauen durch Transparenz, Ehrlichkeit und ethische Praktiken in allen unseren Geschäftsbeziehungen.',
    exclusivityValue: 'Exklusivität',
    exclusivityText: 'Wir bieten unserer ausgewählten Gemeinschaft Zugang zu Möglichkeiten, die auf dem offenen Markt nicht verfügbar sind.',
    joinOurCommunity: 'Tritt Unserer Exklusiven Gemeinschaft Bei',
    joinOurCommunityText: 'EasyROI bietet mehr als nur Investitionen - es bietet die Mitgliedschaft in einem exklusiven Netzwerk anspruchsvoller Investoren, die den Wert erstklassiger Möglichkeiten verstehen.',
    loginCta: 'Zugang zu Deinem Portfolio',
    
    // Footer
    footerDescription: 'Premium-Immobilieninvestitionen in Italien, Dubai und darüber hinaus. Maximiere deinen ROI mit unserem exklusiven Portfolio und Expertenmanagement.',
    quickLinks: 'Schnellzugriff',
    
    // Language change messages
    languageChanged: 'Language changed to English',
    languageChangedItalian: 'Lingua cambiata in Italiano',
    languageChangedSpanish: 'Idioma cambiado a Español',
    languageChangedGerman: 'Sprache auf Deutsch geändert',
    
    // Registration page
    firstNameRequired: 'Vorname ist erforderlich',
    lastNameRequired: 'Nachname ist erforderlich',
    invalidEmail: 'Ungültige E-Mail-Adresse',
    passwordMinChars: 'Passwort muss mindestens 8 Zeichen enthalten',
    acceptTermsRequired: 'Du musst die Allgemeinen Geschäftsbedingungen akzeptieren',
    passwordsNotMatch: 'Passwörter stimmen nicht überein',
    registrationSuccess: 'Registrierung erfolgreich!',
    accountCreated: 'Dein Konto wurde erstellt.',
    firstName: 'Vorname',
    lastName: 'Nachname',
    confirmPassword: 'Passwort bestätigen',
    iAccept: 'Ich akzeptiere die',
    termsAndConditions: 'Allgemeinen Geschäftsbedingungen',
    creatingAccount: 'Konto wird erstellt...',
    alreadyHaveAccount: 'Hast du bereits ein Konto?',
    joinCommunity: 'Tritt unserer exklusiven Investorengemeinschaft bei',
    firstNamePlaceholder: 'Hans',
    lastNamePlaceholder: 'Schmidt',
    
    // Properties page
    filterProperties: 'Immobilien filtern',
    showFilters: 'Filter anzeigen',
    hideFilters: 'Filter ausblenden',
    allLocations: 'Alle Standorte',
    allPrices: 'Alle Preise',
    allLevels: 'Alle Stufen',
    priceRange: 'Preisbereich',
    investorLevel: 'Investorenstufe',
    resetFilters: 'Filter zurücksetzen',
    applyFilters: 'Filter anwenden',
    minInvestment: 'Mindestinvestition',
    expectedROI: 'Erwarteter ROI',
    exclusiveProperties: 'Exklusive Immobilien',
    discoverProperties: 'Entdecke unsere handverlesene Auswahl an Luxusimmobilieninvestitionen an erstklassigen Standorten weltweit.',
    amenities: 'Ausstattung',
    
    // Settings page
    manageSettings: 'Verwalte deine Kontoeinstellungen und Präferenzen',
    accountSettings: 'Kontoeinstellungen',
    accountSettingsDesc: 'Sieh dir deine Kontodaten an und verwalte sie',
    displaySettings: 'Anzeigeeinstellungen',
    displaySettingsDesc: 'Passe deine Anzeigeeinstellungen an',
    notificationSettingsDesc: 'Verwalte deine Benachrichtigungspräferenzen',
    privacySettings: 'Datenschutzeinstellungen',
    privacySettingsDesc: 'Kontrolliere deine Datenschutzeinstellungen',
    name: 'Name',
    selectLanguage: 'Sprache auswählen',
    selectCurrency: 'Währung auswählen',
    selectTimezone: 'Zeitzone auswählen',
    currency: 'Währung',
    timezone: 'Zeitzone',
    emailNotifications: 'E-Mail-Benachrichtigungen',
    emailNotificationsDesc: 'Erhalte Benachrichtigungen per E-Mail',
    pushNotifications: 'Push-Benachrichtigungen',
    pushNotificationsDesc: 'Erhalte Push-Benachrichtigungen',
    publicProfile: 'Öffentliches Profil',
    publicProfileDesc: 'Mache dein Profil für andere Benutzer sichtbar',
    dataSharing: 'Datenaustausch',
    dataSharingDesc: 'Erlaube uns, deine Daten mit Partnern zu teilen',
    saving: 'Speichern...',
    updateAccount: 'Konto Aktualisieren',
    updateDisplay: 'Anzeige Aktualisieren',
    updateNotifications: 'Benachrichtigungen Aktualisieren',
    updatePrivacy: 'Datenschutz Aktualisieren',
    accountSettingsUpdated: 'Kontoeinstellungen Aktualisiert',
    accountSettingsSaved: 'Deine Kontoeinstellungen wurden gespeichert.',
    displaySettingsUpdated: 'Anzeigeeinstellungen Aktualisiert',
    displaySettingsSaved: 'Deine Anzeigeeinstellungen wurden gespeichert.',
    notificationSettingsUpdated: 'Benachrichtigungseinstellungen Aktualisiert',
    notificationSettingsSaved: 'Deine Benachrichtigungseinstellungen wurden gespeichert.',
    privacySettingsUpdated: 'Datenschutzeinstellungen Aktualisiert',
    privacySettingsSaved: 'Deine Datenschutzeinstellungen wurden gespeichert.',
    errorOccurred: 'Fehler Aufgetreten',
    errorLoadingSettings: 'Fehler beim Laden der Einstellungen. Bitte versuche es erneut.',
    errorUpdatingSettings: 'Fehler beim Aktualisieren der Einstellungen. Bitte versuche es erneut.',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [displaySettings, setDisplaySettings] = useState<DisplaySettings>(getInitialSettings);
  const [, setForceUpdate] = useState<number>(0); // Used to force re-render

  useEffect(() => {
    // Save settings to localStorage when they change
    localStorage.setItem('displaySettings', JSON.stringify(displaySettings));
    document.documentElement.lang = displaySettings.language;
    
    // Force a re-render of the entire application
    setForceUpdate(prev => prev + 1);
  }, [displaySettings]);

  const updateDisplaySettings = (newSettings: Partial<DisplaySettings>) => {
    setDisplaySettings(prev => ({ ...prev, ...newSettings }));
  };

  // Translation function
  const t = (key: string): string => {
    const currentLanguage = displaySettings.language;
    return translations[currentLanguage]?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ displaySettings, updateDisplaySettings, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
