
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import type { SupabaseRPC } from './rpcTypes';

const SUPABASE_URL = "https://gqsetnzdaocxmutrbisp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdxc2V0bnpkYW9jeG11dHJiaXNwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQwMzE3OTksImV4cCI6MjA1OTYwNzc5OX0.KQK4wmrm2AHOs-IL35PpUaZ51GWKELEjg06axvCXV7M";

// Create the typed client
export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY
) as ReturnType<typeof createClient> & { rpc: SupabaseRPC['rpc'] };
